"use client";
import Link from "next/link";
import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api"; // generated by convex dev
import { useRouter } from "next/navigation";

export default function BlogList() {
  const posts = useQuery(api.posts.listPosts, { limit: 100 }) ?? [];
  const router = useRouter();

  const goToNewPost = () => {
    router.push("/blog/new");
  };
  return (
    <main className="max-w-2xl mx-auto p-6 space-y-4">
      <h1 className="text-3xl font-bold">Blog</h1>
      <button onClick={goToNewPost} className="underline">Create a post (admins)</button>
      <ul className="space-y-3">
        {posts.map(p => (
          <li key={p._id}>
            <Link className="text-xl underline" href={`/blog/${p.slug}`}>{p.title}</Link>
            <div className="text-sm opacity-70">
              by {p.authorAlias} • {new Date(p.createdAt).toLocaleString()}
            </div>
          </li>
        ))}
      </ul>
      <Link href="/" className="bg-black text-white px-4 py-2 rounded-lg hover:bg-gray-800 transition-colors mt-4 block mx-auto w-fit">
        ← Back to landing
      </Link>
    </main>
  );
}
